apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: audiobooks
  name: audiobooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobooks
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: audiobooks
    spec:
      containers:
      - image: ghcr.io/advplyr/audiobookshelf:2.26.1
        name: audiobookshelf
        ports:
        - containerPort: 3005
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: audiobooks-config
              key: APP_PORT
