apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: audiobooks
  name: audiobooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobooks
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: audiobooks
    spec:
      securityContext:
        fsGroup: 1000 # node user
        runAsUser: 1000 # node user
        runAsGroup: 1000 # node user
      containers:
      - image: ghcr.io/advplyr/audiobookshelf:2.26.1
        name: audiobookshelf
        ports:
        - containerPort: 3005
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: audiobooks-config
              key: APP_PORT


        volumeMounts:
          - name: audiobooks-data
            mountPath: /audiobooks
          - name: podcasts-data
            mountPath: /podcasts
          - name: config-data
            mountPath: /config
          - name: metadata-data
            mountPath: /metadata

        securityContext:
          allowPrivilegeEscalation: false

      volumes:
        - name: audiobooks-data
          persistentVolumeClaim:
            claimName: audiobooks-data-pvc

        - name: podcasts-data
          persistentVolumeClaim:
            claimName: podcasts-data-pvc

        - name: config-data
          persistentVolumeClaim:
            claimName: config-data-pvc

        - name: metadata-data
          persistentVolumeClaim:
            claimName: metadata-data-pvc
