apiVersion: v1
data:
    password: ENC[AES256_GCM,data:1O1uD6aYJZw=,iv:0E2+N8C/X0JVJaD1zRCZQ3dvR0dtN035C9JQFhcvA5w=,tag:PGzrWNmREI4M3S5FwYZjPw==,type:str]
    user: ENC[AES256_GCM,data:lT3ZZBtAnWY=,iv:TCIevpuei6TvLNaDfs2/M/hvy0XGwI0/6yqN6i2fvOY=,tag:WTdm6TFVGC55FOzBGwUWNQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-tls-secret
sops:
    age:
        - recipient: age1apkjzd0nu99dg737jsvjnxueeugvehyjtrfcq30xkv2f9cvewcns60xyke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4elJHUlk1TVBXZGJ2RnJN
            Q0s1aWNKNjFKRG9nSEZkdlJWdDJrVnFNY3k4ClhzenhnODV0N2VEZGpJUkxxL3B5
            Rm9tMXNLSStkSkNzWklyNE4xVi80ZDgKLS0tIEVqazlXRnVrRmVpelZOY1YvSmM4
            eEk1MDNQdDlxenlpcWZlMkZhUVUzNW8KS5HECyvFNHFO5z4HUwRAM6DHN3AIq15Q
            PPcNmjaVJ6dpgmPygN92vvumel2OlbbVhLb54vUlc4K/k60D2INiWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T15:01:15Z"
    mac: ENC[AES256_GCM,data:OPaaZzQdF6IcibBe9SwwkQhyxI6jIpMVEQfpwINJNzkK+bgj7lVrYKq0T+eZ0n3YL933K2j49ofuO08g0JgdM6PHVZIx8jF7ShGD/3AxErHSORcuSonOFjbb8r1D0YjeoF0jmLeuM9qZGqtLpXgrw/pwnC3k3gBqkDK+d/AyUNE=,iv:wVz/FzaVxScsjtNYp3Xllfn4PZLQZV9k4lRp59tcPcM=,tag:OJ+ECYTbNXjjITO/3R180g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
