apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audiobooks
spec:
  ingressClassName: traefik
  rules:
    - host: audiobooks.cloudcentral.tech
      http:
        paths:
          - backend:
              service:
                name: audiobooks
                port:
                  number: 3005
            path: /
            pathType: Prefix
