apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding
  #- tunnel-config.yaml
  - cloudflare-secret.yaml
  - linkding-container-env-secret.yaml 
