apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:KZl4yRt3RReqR3itwDKHNaNZkdFwyQs5wZDHeZDXe8+NatILdpxPtlcwMSGmoJyN5HqW2ay6eE8Mp5hrJM75hRJlQXoVoMJqf99VumnILuP3kJcvMyhsO0lpxwOOEDg54230vU3IuusPFA3VLRbpDJ3ZqombJJbq2SQcIdA9BXawjOCVWKtFprC0/mqFNB1HwDZVlZd03rv73NeaDlFtY/0qVoxEAX6vh/YfPZdpoYjQzdrwYXGbYM0xO/yeMYRL0unMF5BvbZHH7Zv/Eg35u+AbfP/+KwtPMN8fVeML3nBsElo8a0eNCtvMLEE=,iv:Hm/MluiQZPQgF+90Y/rZ43iDOWzrx23frw7LuMOLSrM=,tag:1eaLrdcpogzffEW8yslWfw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-tls-secret
    namespace: monitoring
sops:
    age:
        - recipient: age1apkjzd0nu99dg737jsvjnxueeugvehyjtrfcq30xkv2f9cvewcns60xyke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTWoydFB4dy90Ulk4Unp2
            WVdKNExTdmcyVnllRTU3MncxRnpyNzBVSWdZCjY2c0tSRGQwTlV0bU1JN040SHpu
            QktsaTJBMkRLeG13aExQSkh0cFhZTDAKLS0tIDBnM3ppdThRWGxPNTR1ZUlMVWQr
            WWNQSE9veWxJNWJtWWZoNnl1TUlLYnMKOzjfTOjcVwCoMr2Znk7pYEKjIpm8g6VK
            GI/SAy7vGV6ISlPPzLaFE7N5a1bG6dqlJDV69pdZmimIWJlr5CK3Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T19:37:44Z"
    mac: ENC[AES256_GCM,data:2bXgYgo2bNBA7aoxmoLCOJmW6w78Jvxi/V23SGw8C4SmFODmlGSt2IQFWm4RP2SXqWxbWf12cChF9FK0ZoZL2Tt6T0ZdYa5dJTVU5G4TK+XEjCIX8sm6ERPumcQywPy6rHAQluYlClcqOtNQV/z57UBu3KBPnArMenaUyVtOsU4=,iv:4t6em59Yz4A04GZei+AYQ3k5aOduPA3pe5w8bRvgksY=,tag:B7u4MPNCebQvajnJh1tYEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
